#spring:
#    profiles: h2
#    datasource:
#        driver-class-name: org.h2.Driver
#        url: jdbc:h2:mem:db;
#        username: sa
#        password: sa
#    jpa:
#        show-sql: false
#        database-platform: org.hibernate.dialect.H2Dialect
#    h2:
#        console:
#            enabled: true
#
#---
spring:
    datasource:
        url: "jdbc:sqlserver://srvpandora.database.windows.net:1433;database=pandora"
        username: "pandora@srvpandora"
        password: "#Gfgrupo3"
    jpa:
        database-platform: org.hibernate.dialect.SQLServer2012Dialect
        show-sql: true
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.SQLServer2012Dialect
